let
  Source = Excel.Workbook(File.Contents("C:\Users\Asus\Desktop\Assignments\Case Analysis\Raw\RMS_Cases_Synthetic_Raw.xlsx"), null, true),
    #"Filtered Rows" = Table.SelectRows(Source, each ([Name] <> "About")),
    #"Removed Other Columns" = Table.SelectColumns(#"Filtered Rows",{"Data", "Name"}),
    #"Added Custom" = Table.AddColumn(#"Removed Other Columns", "Clean", each Table.RenameColumns(
        Table.TransformColumnNames(Table.PromoteHeaders([Data]), Text.Trim),
        {{"Seller Name", "Seller's Name"}, {"No of ASINs", "No. of ASIN"}, {"Case Link", "Case"}},
        MissingField.Ignore)),
    #"Removed Columns" = Table.RemoveColumns(#"Added Custom",{"Data"}),
    #"Renamed Columns" = Table.RenameColumns(#"Removed Columns",{{"Name", "Month"}}),
    #"Expanded Clean" = Table.ExpandTableColumn(#"Renamed Columns", "Clean", {"Case", "Date Opened", "Date Closed", "FC", "Marketplace", "Region", "Root Cause", "RMS Given", "No. of ASIN", "RMS Amount", "Shipment Type", "Carrier", "Re-Evaluation", "Approved", "Re-Evaluation Amount", "Seller's Name"}, {"Case", "Date Opened", "Date Closed", "FC", "Marketplace", "Region", "Root Cause", "RMS Given", "No. of ASIN", "RMS Amount", "Shipment Type", "Carrier", "Re-Evaluation", "Approved", "Re-Evaluation Amount", "Seller's Name"}),
    #"Filtered Rows1" = Table.SelectRows(#"Expanded Clean", each ([Case] <> null and [Case] <> "TOTAL")),
    #"Changed Type" = Table.TransformColumnTypes(#"Filtered Rows1",{{"Case", type text}}),
    #"Replaced Value" = Table.ReplaceValue(#"Changed Type","https://casetool.example.com/view?caseId=","",Replacer.ReplaceText,{"Case"}),
    #"Removed Duplicates" = Table.Distinct(#"Replaced Value", {"Case"}),
    #"Changed Type with Locale" = Table.TransformColumnTypes(#"Removed Duplicates", {{"Date Opened", type date}}, "en-GB"),
    #"Changed Type with Locale1" = Table.TransformColumnTypes(#"Changed Type with Locale", {{"Date Closed", type date}}, "en-GB"),
    #"Changed Type1" = Table.TransformColumnTypes(#"Changed Type with Locale1",{{"RMS Amount", type text}}),
    #"Replaced Value1" = Table.ReplaceValue(#"Changed Type1","€","",Replacer.ReplaceText,{"RMS Amount"}),
    #"Replaced Value2" = Table.ReplaceValue(#"Replaced Value1","£","",Replacer.ReplaceText,{"RMS Amount"}),
    #"Replaced Value3" = Table.ReplaceValue(#"Replaced Value2","C$","",Replacer.ReplaceText,{"RMS Amount"}),
    #"Replaced Value4" = Table.ReplaceValue(#"Replaced Value3","$","",Replacer.ReplaceText,{"RMS Amount"}),
    #"Replaced Value5" = Table.ReplaceValue(#"Replaced Value4",",","",Replacer.ReplaceText,{"RMS Amount"}),
    #"Changed Type2" = Table.TransformColumnTypes(#"Replaced Value5",{{"RMS Amount", type number}, {"Re-Evaluation Amount", type text}}),
    #"Replaced Value6" = Table.ReplaceValue(#"Changed Type2","No","0",Replacer.ReplaceText,{"Re-Evaluation Amount"}),
    #"Changed Type3" = Table.TransformColumnTypes(#"Replaced Value6",{{"Re-Evaluation Amount", type number}, {"No. of ASIN", Int64.Type}}),
    #"Calculated Absolute Value" = Table.TransformColumns(#"Changed Type3",{{"No. of ASIN", Number.Abs, Int64.Type}}),
    #"Trimmed Text" = Table.TransformColumns(#"Calculated Absolute Value",{{"Marketplace", Text.Trim, type text}}),
    #"Uppercased Text" = Table.TransformColumns(#"Trimmed Text",{{"Marketplace", Text.Upper, type text}}),
    #"Removed Columns1" = Table.RemoveColumns(#"Uppercased Text",{"Region"}),
    #"Added Conditional Column" = Table.AddColumn(#"Removed Columns1", "Region", each if [Marketplace] = "US" then "NA" else if [Marketplace] = "CA" then "NA" else "EU"),
    #"Reordered Columns" = Table.ReorderColumns(#"Added Conditional Column",{"Month", "Case", "Date Opened", "Date Closed", "FC", "Marketplace", "Region", "Root Cause", "RMS Given", "No. of ASIN", "RMS Amount", "Shipment Type", "Carrier", "Re-Evaluation", "Approved", "Re-Evaluation Amount", "Seller's Name"}),
    #"Trimmed Text1" = Table.TransformColumns(#"Reordered Columns",{{"RMS Given", Text.Trim, type text}, {"Re-Evaluation", Text.Trim, type text}, {"Approved", Text.Trim, type text}}),
    #"Capitalized Each Word" = Table.TransformColumns(#"Trimmed Text1",{{"RMS Given", Text.Proper, type text}, {"Re-Evaluation", Text.Proper, type text}, {"Approved", Text.Proper, type text}}),
    #"Replaced Value7" = Table.ReplaceValue(#"Capitalized Each Word","N","No",Replacer.ReplaceValue,{"RMS Given"}),
    #"Replaced Value8" = Table.ReplaceValue(#"Replaced Value7","Y","Yes",Replacer.ReplaceValue,{"RMS Given"}),
    #"Replaced Value9" = Table.ReplaceValue(#"Replaced Value8",null,"Unknown",Replacer.ReplaceValue,{"Carrier"}),
    #"Replaced Value10" = Table.ReplaceValue(#"Replaced Value9","U.P.S.","UPS",Replacer.ReplaceText,{"Carrier"}),
    #"Replaced Value11" = Table.ReplaceValue(#"Replaced Value10","DHL Express","DHL",Replacer.ReplaceText,{"Carrier"}),
    #"Replaced Value12" = Table.ReplaceValue(#"Replaced Value11","Dhl","DHL",Replacer.ReplaceText,{"Carrier"}),
    #"Uppercased Text1" = Table.TransformColumns(#"Replaced Value12",{{"Carrier", Text.Upper, type text}}),
    #"Replaced Value14" = Table.ReplaceValue(#"Uppercased Text1","JB HUNT TRANSPORT","JB HUNT",Replacer.ReplaceText,{"Carrier"}),
    #"Replaced Value15" = Table.ReplaceValue(#"Replaced Value14","J.B. HUNT","JB HUNT",Replacer.ReplaceText,{"Carrier"}),
    #"Replaced Value16" = Table.ReplaceValue(#"Replaced Value15","ESTES","ESTES EXPRESS",Replacer.ReplaceValue,{"Carrier"}),
    #"Trimmed Text2" = Table.TransformColumns(#"Replaced Value16",{{"Carrier", Text.Trim, type text}}),
    #"Replaced Value13" = Table.ReplaceValue(#"Trimmed Text2",";",",",Replacer.ReplaceText,{"Root Cause"}),
    #"Lowercased Text" = Table.TransformColumns(#"Replaced Value13",{{"Root Cause", Text.Lower, type text}}),
    #"Capitalized Each Word1" = Table.TransformColumns(#"Lowercased Text",{{"Root Cause", Text.Proper, type text}}),
    #"Replaced Value17" = Table.ReplaceValue(#"Capitalized Each Word1","  "," ",Replacer.ReplaceText,{"Root Cause"}),
    #"Replaced Value18" = Table.ReplaceValue(#"Replaced Value17"," ,",",",Replacer.ReplaceText,{"Root Cause"}),
    #"Trimmed Text3" = Table.TransformColumns(#"Replaced Value18",{{"Root Cause", Text.Trim, type text}}),
    #"Replaced Value19" = Table.ReplaceValue(#"Trimmed Text3","Fc Operation","FC Operation",Replacer.ReplaceText,{"Root Cause"}),
    #"Replaced Value20" = Table.ReplaceValue(#"Replaced Value19","No Id","No ID",Replacer.ReplaceText,{"Root Cause"}),
    #"Replaced Value21" = Table.ReplaceValue(#"Replaced Value20","By Seller","by seller",Replacer.ReplaceText,{"Root Cause"}),
    #"Replaced Value22" = Table.ReplaceValue(#"Replaced Value21","In Full","in Full",Replacer.ReplaceText,{"Root Cause"}),
    #"Replaced Value23" = Table.ReplaceValue(#"Replaced Value22",null,"Unknown",Replacer.ReplaceValue,{"FC", "Shipment Type", "Seller's Name"}),
    #"Reordered Columns1" = Table.ReorderColumns(#"Replaced Value23",{"Case", "Month", "Date Opened", "Date Closed", "FC", "Marketplace", "Region", "Root Cause", "RMS Given", "No. of ASIN", "RMS Amount", "Shipment Type", "Carrier", "Re-Evaluation", "Approved", "Re-Evaluation Amount", "Seller's Name"}),
    #"Changed Type4" = Table.TransformColumnTypes(#"Reordered Columns1",{{"FC", type text}, {"Seller's Name", type text}, {"Shipment Type", type text}, {"Region", type text}}),
    #"Sorted Rows" = Table.Sort(#"Changed Type4",{{"Case", Order.Ascending}}),
  #"Inserted conditional column" = Table.AddColumn(#"Sorted Rows", "Shipment Partnership", each if [Carrier] = "UNKNOWN" then "Non-Partnered" else "Partnered")
in
    #"Inserted conditional column"
